# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16SC6bLMBAEpH6hbOO3FdzDeREqv_JwXz
"""

import pandas as pd
import numpy as np
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
BaseDados = pd.read_excel('Dados_Bitcoin.xlsx')
BaseDados.set_index("Date", inplace=True)

MediaMovel = BaseDados['Close'].rolling(5).mean()
MediaTendencia = BaseDados['Close'].rolling(30).mean()

figura = go.Figure()


figura.add_trace(
    go.Scatter(
        x = BaseDados.index,
        y = MediaMovel,
        mode="lines",
        name='Média movel',
        marker_color="#ff7f0e"
    )
)

figura.add_trace(
    go.Scatter(
        x = BaseDados.index,
        y = BaseDados.Close,
        mode="lines",
        name='Fechamento',
        marker_color="Red"
    )
)

figura.add_trace(
    go.Scatter(
        x = BaseDados.index,
        y = MediaTendencia,
        mode="lines",
        name='Tendência',
        marker_color="Blue"
    )
)

figura.update_layout(
    title="Análise de Bitcoin",
    titlefont_size=20,
    xaxis = dict(
        title='Período',
        titlefont_size=13,
        tickfont_size=10
    ),
    yaxis = dict(
        title='Fechamento',
        titlefont_size=13,
        tickfont_size=10
    )
)

figura.show()